# Generated by Django 5.1.2 on 2024-10-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('birthdate', models.DateField()),
                ('death', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='editors')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books')),
                ('summary', models.TextField()),
                ('isbn', models.CharField(max_length=13)),
                ('language', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('format', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.author')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.editor')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('note', models.IntegerField()),
                ('visibility', models.BooleanField()),
                ('moderate', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.book')),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50)),
                ('acquisition_date', models.DateField()),
                ('localisation', models.CharField(max_length=50)),
                ('availability', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.book')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.TextField()),
                ('date', models.DateField()),
                ('note', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('recommended', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.book')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField()),
                ('return_date_expected', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.copy')),
            ],
        ),
    ]
